INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (1, 'Tony', 'Abernathy', '1989-02-06', 'Idaho');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (2, 'Leandro', 'Langosh', '1992-09-04', 'Mississippi');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (3, 'Quincy', 'Haley', '1971-08-14', 'Virginia');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (4, 'Deandrea', 'Runolfsdottir', '1995-10-17', 'South Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (5, 'Geraldo', 'Leuschke', '2004-11-15', 'Connecticut');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (6, 'Lemuel', 'Waelchi', '1978-05-01', 'Washington');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (7, 'Jonas', 'Rempel', '1964-01-06', 'Kentucky');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (8, 'Josef', 'Hoppe', '1988-02-17', 'Ohio');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (9, 'Magda', 'McClure', '1959-05-09', 'Arkansas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (10, 'Stevie', 'Wolff', '1986-01-13', 'Kansas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (11, 'Perry', 'Prosacco', '1966-09-12', 'Tennessee');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (12, 'Devin', 'Ernser', '1989-04-17', 'Arkansas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (13, 'Sandra', 'Krajcik', '1972-01-25', 'Vermont');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (14, 'Kathryn', 'Murphy', '1962-02-05', 'Michigan');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (15, 'Jannie', 'Mohr', '1989-07-30', 'New Mexico');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (16, 'Augustine', 'Gibson', '2001-09-27', 'Oklahoma');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (17, 'Noe', 'Bailey', '1981-01-20', 'Tennessee');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (18, 'Juliane', 'Torphy', '1960-05-27', 'Nevada');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (19, 'Eugenia', 'Hammes', '1995-06-26', 'South Carolina');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (20, 'Jannet', 'Lindgren', '1988-06-13', 'Wyoming');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (21, 'Janae', 'Larkin', '1993-10-26', 'Alabama');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (22, 'Dean', 'Kling', '1998-06-27', 'Utah');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (23, 'Lovetta', 'Marvin', '1972-09-07', 'Iowa');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (24, 'Pilar', 'Block', '1979-03-24', 'Mississippi');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (25, 'Rosario', 'Heaney', '2002-08-17', 'Hawaii');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (26, 'Lavenia', 'Tillman', '1979-11-04', 'Arizona');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (27, 'Moses', 'Herman', '1983-03-10', 'Indiana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (28, 'Benedict', 'Bradtke', '1971-04-05', 'Florida');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (29, 'Greg', 'Osinski', '1970-05-22', 'New Jersey');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (30, 'Ian', 'Trantow', '1960-02-06', 'Texas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (31, 'Mable', 'Wilderman', '1978-06-14', 'Missouri');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (32, 'Loida', 'Mraz', '1977-06-27', 'Rhode Island');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (33, 'Anabel', 'O''Keefe', '1980-10-25', 'Washington');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (34, 'Ella', 'Nikolaus', '1983-06-22', 'South Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (35, 'Curt', 'Casper', '2003-10-03', 'Nevada');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (36, 'Tim', 'Goyette', '1963-05-26', 'Maryland');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (37, 'Reanna', 'Runolfsson', '1975-07-29', 'South Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (38, 'Johnnie', 'Turcotte', '1965-11-04', 'Wisconsin');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (39, 'Charisse', 'Kertzmann', '1993-02-16', 'Vermont');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (40, 'Gabriela', 'Runte', '1994-05-14', 'Illinois');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (41, 'Gina', 'Beer', '1992-01-06', 'Delaware');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (42, 'Karleen', 'Heidenreich', '1993-03-08', 'Kansas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (43, 'Rodrigo', 'Schuppe', '1999-11-05', 'Mississippi');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (44, 'Tia', 'Sauer', '1986-08-11', 'Utah');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (45, 'Marcene', 'Hintz', '2003-12-25', 'Maryland');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (46, 'Edward', 'Kohler', '1999-03-18', 'Wyoming');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (47, 'Alonso', 'Johns', '1969-08-31', 'Tennessee');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (48, 'Fabiola', 'Schmitt', '1968-03-27', 'California');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (49, 'Gerald', 'Hane', '1976-02-25', 'Maine');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (50, 'Nella', 'Predovic', '1985-10-02', 'Texas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (51, 'Marcel', 'Durgan', '1974-01-29', 'Mississippi');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (52, 'Garth', 'Koss', '1990-07-24', 'Indiana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (53, 'Boris', 'Corwin', '1961-10-14', 'Kentucky');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (54, 'Sergio', 'Jones', '1998-05-13', 'Missouri');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (55, 'Minh', 'Rempel', '1967-12-30', 'Delaware');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (56, 'Dian', 'Bashirian', '1963-08-20', 'Iowa');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (57, 'Malisa', 'Rohan', '1985-01-16', 'Montana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (58, 'Inell', 'Streich', '1984-10-14', 'Oregon');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (59, 'Clarinda', 'Rosenbaum', '1964-09-03', 'Nevada');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (60, 'Myles', 'Schiller', '1982-07-15', 'Illinois');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (61, 'Bessie', 'Pouros', '1971-06-06', 'Florida');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (62, 'Lottie', 'Miller', '1972-06-03', 'Wisconsin');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (63, 'Marty', 'Cummings', '1969-04-09', 'Vermont');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (64, 'Ernestine', 'Barrows', '1988-10-08', 'California');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (65, 'Hee', 'Stracke', '1992-09-19', 'Pennsylvania');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (66, 'Bart', 'Rippin', '1998-02-20', 'South Carolina');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (67, 'Chris', 'Jacobson', '1981-03-05', 'Alaska');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (68, 'Yuonne', 'King', '1986-01-29', 'Ohio');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (69, 'Greg', 'Legros', '2003-10-18', 'Colorado');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (70, 'Spencer', 'Tremblay', '1972-07-31', 'Delaware');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (71, 'Jody', 'Considine', '1972-01-12', 'Illinois');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (72, 'Zachariah', 'Wilderman', '1962-10-23', 'Massachusetts');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (73, 'Elyse', 'Nolan', '1969-02-04', 'North Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (74, 'Oswaldo', 'Tromp', '1971-02-24', 'West Virginia');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (75, 'Levi', 'Schinner', '1998-10-13', 'Alaska');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (76, 'Barton', 'Labadie', '2001-06-12', 'Arkansas');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (77, 'Aurore', 'Ratke', '1971-03-07', 'Minnesota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (78, 'Ramon', 'Durgan', '1973-10-04', 'Nebraska');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (79, 'Junior', 'Treutel', '1990-06-13', 'Alabama');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (80, 'Penelope', 'Schultz', '1967-11-28', 'Maryland');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (81, 'Clarine', 'Bahringer', '1985-05-17', 'Utah');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (82, 'Merrilee', 'Kub', '1997-10-20', 'Oregon');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (83, 'Albert', 'Hilll', '1976-03-19', 'Georgia');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (84, 'Dara', 'Luettgen', '1980-04-23', 'Georgia');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (85, 'Richard', 'Considine', '1992-07-23', 'Louisiana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (86, 'Phil', 'Kovacek', '1975-04-07', 'Oregon');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (87, 'Camila', 'White', '1995-04-10', 'North Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (88, 'Brendon', 'Little', '1993-11-23', 'Kentucky');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (89, 'Shaun', 'Stokes', '1990-09-28', 'Utah');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (90, 'Kaylee', 'Windler', '1964-03-05', 'Washington');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (91, 'Elmer', 'McCullough', '2003-02-04', 'Nevada');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (92, 'Toney', 'Anderson', '1970-06-06', 'Louisiana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (93, 'Javier', 'Bins', '1973-10-09', 'California');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (94, 'Yan', 'Gottlieb', '2001-12-19', 'Delaware');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (95, 'Gabriel', 'Stoltenberg', '1961-07-06', 'Massachusetts');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (96, 'Marinda', 'Koelpin', '1961-07-19', 'Wisconsin');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (97, 'Keren', 'Zboncak', '1988-06-01', 'North Dakota');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (98, 'Man', 'Hettinger', '1971-05-04', 'Nevada');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (99, 'Elza', 'Nolan', '1970-12-18', 'Montana');
INSERT INTO gestionale.clienti (NumeroCliente, Nome, Cognome, DataNascita, RegioneResidenza) VALUES (100, 'Lamar', 'Leannon', '1980-05-02', 'Georgia');
