INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (1, 'Ziemann, Satterfield and Conn', 'South Carolina');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (2, 'Mitchell Inc', 'Massachusetts');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (3, 'Kozey Inc', 'Alaska');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (4, 'Hessel-Collier', 'Massachusetts');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (5, 'Emmerich-Quigley', 'Alaska');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (6, 'Mills Group', 'Florida');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (7, 'Franecki LLC', 'California');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (8, 'Bartoletti, Marquardt and Schultz', 'Alabama');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (9, 'Orn, Beahan and Fritsch', 'Oklahoma');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (10, 'Steuber-Lubowitz', 'West Virginia');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (11, 'Grady and Sons', 'Mississippi');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (12, 'Gutkowski, Roob and Johnston', 'Delaware');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (13, 'Mueller-Volkman', 'Pennsylvania');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (14, 'Pouros, Nader and Welch', 'Indiana');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (15, 'Bogan Inc', 'Nebraska');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (16, 'Heller Inc', 'California');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (17, 'Okuneva, Donnelly and Harber', 'Oregon');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (18, 'Bins, Thompson and Mante', 'Maine');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (19, 'Ondricka, Reinger and Bauch', 'Mississippi');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (20, 'Fay, Stokes and Schuster', 'Oregon');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (21, 'Douglas-Spinka', 'Maryland');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (22, 'Cronin, Gleichner and Predovic', 'New Jersey');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (23, 'Kutch, Daniel and Trantow', 'Texas');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (24, 'Brakus-Kreiger', 'Pennsylvania');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (25, 'Crist, O''Hara and Dach', 'Wyoming');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (26, 'Hartmann Group', 'New Jersey');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (27, 'Boyle-Torphy', 'California');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (28, 'Kuphal Inc', 'West Virginia');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (29, 'Ebert LLC', 'Georgia');
INSERT INTO gestionale.fornitori (numerofornitore, denominazione, regioneresidenza) VALUES (30, 'Reichel-Rohan', 'Virginia');
